
// Code generated by stanc fa623df
#include <stan/model/model_header.hpp>
namespace m7x462s_model_namespace {


inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 

stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 9, column 1 to column 8)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 10, column 1 to column 13)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 11, column 1 to column 16)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 15, column 4 to column 17)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 25, column 1 to column 19)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 26, column 1 to column 12)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 28, column 2 to column 52)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 27, column 1 to line 28, column 52)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 29, column 1 to column 15)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 20, column 1 to column 20)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 21, column 1 to column 19)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 22, column 1 to column 28)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 2, column 2 to column 22)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 3, column 2 to column 22)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 4, column 9 to column 10)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 4, column 2 to column 18)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 5, column 9 to column 10)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 5, column 12 to column 13)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 5, column 2 to column 20)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 10, column 8 to column 9)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 15, column 11 to column 12)",
                                                      " (in '/Users/rob/.julia/dev/StatisticalRethinkingStan/tmp/m7.2s.stan', line 25, column 8 to column 9)"};



class m7x462s_model final : public model_base_crtp<m7x462s_model> {

 private:
  double lcm_sym30__;
  double lcm_sym29__;
  double lcm_sym28__;
  double lcm_sym27__;
  int lcm_sym26__;
  int lcm_sym25__;
  int lcm_sym24__;
  int N;
  int K;
  Eigen::Matrix<double, -1, 1> brain;
  Eigen::Matrix<double, -1, -1> mass;
 
 public:
  ~m7x462s_model() { }
  
  inline std::string model_name() const final { return "m7x462s_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 fa623df", "stancflags = --warn-pedantic --O"};
  }
  
  
  m7x462s_model(stan::io::var_context& context__,
                unsigned int random_seed__ = 0,
                std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "m7x462s_model_namespace::m7x462s_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      
      
      
      
      
      
      
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 13;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 13;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 13;
      current_statement__ = 13;
      check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 14;
      context__.validate_dims("data initialization","K","int",
          context__.to_vec());
      K = std::numeric_limits<int>::min();
      
      current_statement__ = 14;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 14;
      current_statement__ = 14;
      check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 15;
      validate_non_negative_index("brain", "N", N);
      current_statement__ = 16;
      context__.validate_dims("data initialization","brain","double",
          context__.to_vec(N));
      brain = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(brain, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<double> brain_flat__;
        current_statement__ = 16;
        assign(brain_flat__, nil_index_list(), context__.vals_r("brain"),
          "assigning variable brain_flat__");
        current_statement__ = 16;
        pos__ = 1;
        lcm_sym25__ = logical_gte(N, 1);
        if (lcm_sym25__) {
          current_statement__ = 16;
          assign(brain, cons_list(index_uni(1), nil_index_list()),
            brain_flat__[(1 - 1)], "assigning variable brain");
          current_statement__ = 16;
          pos__ = 2;
          for (int sym1__ = 2; sym1__ <= N; ++sym1__) {
            current_statement__ = 16;
            assign(brain, cons_list(index_uni(sym1__), nil_index_list()),
              brain_flat__[(pos__ - 1)], "assigning variable brain");
            current_statement__ = 16;
            pos__ = (pos__ + 1);}
        } 
      }
      current_statement__ = 17;
      validate_non_negative_index("mass", "N", N);
      current_statement__ = 18;
      validate_non_negative_index("mass", "K", K);
      current_statement__ = 19;
      context__.validate_dims("data initialization","mass","double",
          context__.to_vec(N, K));
      mass = Eigen::Matrix<double, -1, -1>(N, K);
      stan::math::fill(mass, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<double> mass_flat__;
        current_statement__ = 19;
        assign(mass_flat__, nil_index_list(), context__.vals_r("mass"),
          "assigning variable mass_flat__");
        current_statement__ = 19;
        pos__ = 1;
        current_statement__ = 19;
        if (logical_gte(K, 1)) {
          current_statement__ = 19;
          if (lcm_sym25__) {
            current_statement__ = 19;
            assign(mass,
              cons_list(index_uni(1),
                cons_list(index_uni(1), nil_index_list())),
              mass_flat__[(1 - 1)], "assigning variable mass");
            current_statement__ = 19;
            pos__ = 2;
            for (int sym2__ = 2; sym2__ <= N; ++sym2__) {
              current_statement__ = 19;
              assign(mass,
                cons_list(index_uni(sym2__),
                  cons_list(index_uni(1), nil_index_list())),
                mass_flat__[(pos__ - 1)], "assigning variable mass");
              current_statement__ = 19;
              pos__ = (pos__ + 1);}
          } 
          for (int sym1__ = 2; sym1__ <= K; ++sym1__) {
            current_statement__ = 19;
            if (lcm_sym25__) {
              current_statement__ = 19;
              assign(mass,
                cons_list(index_uni(1),
                  cons_list(index_uni(sym1__), nil_index_list())),
                mass_flat__[(pos__ - 1)], "assigning variable mass");
              current_statement__ = 19;
              pos__ = (pos__ + 1);
              for (int sym2__ = 2; sym2__ <= N; ++sym2__) {
                current_statement__ = 19;
                assign(mass,
                  cons_list(index_uni(sym2__),
                    cons_list(index_uni(sym1__), nil_index_list())),
                  mass_flat__[(pos__ - 1)], "assigning variable mass");
                current_statement__ = 19;
                pos__ = (pos__ + 1);}
            } }
        } 
      }
      current_statement__ = 20;
      validate_non_negative_index("b", "K", K);
      current_statement__ = 21;
      validate_non_negative_index("mu", "N", N);
      current_statement__ = 22;
      validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += K;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "m7x462s_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      double lcm_sym23__;
      double lcm_sym22__;
      double lcm_sym21__;
      Eigen::Matrix<local_scalar_t__, -1, 1> lcm_sym20__;
      local_scalar_t__ a;
      a = DUMMY_VAR__;
      
      current_statement__ = 1;
      a = in__.scalar();
      Eigen::Matrix<local_scalar_t__, -1, 1> b;
      b = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(b, DUMMY_VAR__);
      
      current_statement__ = 2;
      b = in__.vector(K);
      local_scalar_t__ log_sigma;
      log_sigma = DUMMY_VAR__;
      
      current_statement__ = 3;
      log_sigma = in__.scalar();
      Eigen::Matrix<local_scalar_t__, -1, 1> mu;
      mu = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      stan::math::fill(mu, DUMMY_VAR__);
      
      assign(lcm_sym20__, nil_index_list(), add(a, multiply(mass, b)),
        "assigning variable lcm_sym20__");
      assign(mu, nil_index_list(), lcm_sym20__, "assigning variable mu");
      {
        current_statement__ = 10;
        lp_accum__.add(normal_lpdf<propto__>(a, 0.5, 1));
        current_statement__ = 11;
        lp_accum__.add(normal_lpdf<propto__>(b, 0, 10));
        current_statement__ = 12;
        lp_accum__.add(normal_lpdf<propto__>(brain, lcm_sym20__, 0.001));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "m7x462s_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      double lcm_sym19__;
      double lcm_sym18__;
      double lcm_sym17__;
      double lcm_sym16__;
      double lcm_sym15__;
      double lcm_sym14__;
      double lcm_sym13__;
      double lcm_sym12__;
      Eigen::Matrix<double, -1, 1> lcm_sym11__;
      int lcm_sym10__;
      int lcm_sym9__;
      int lcm_sym8__;
      int lcm_sym7__;
      double a;
      a = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      a = in__.scalar();
      Eigen::Matrix<double, -1, 1> b;
      b = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(b, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      b = in__.vector(K);
      double log_sigma;
      log_sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      log_sigma = in__.scalar();
      Eigen::Matrix<double, -1, 1> mu;
      mu = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(mu, std::numeric_limits<double>::quiet_NaN());
      
      vars__.emplace_back(a);
      if (logical_gte(K, 1)) {
        vars__.emplace_back(b[(1 - 1)]);
        for (int sym1__ = 2; sym1__ <= K; ++sym1__) {
          vars__.emplace_back(b[(sym1__ - 1)]);}
      } 
      vars__.emplace_back(log_sigma);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      assign(lcm_sym11__, nil_index_list(), add(a, multiply(mass, b)),
        "assigning variable lcm_sym11__");
      assign(mu, nil_index_list(), lcm_sym11__, "assigning variable mu");
      if (emit_transformed_parameters__) {
        {
          lcm_sym8__ = logical_gte(N, 1);
          if (lcm_sym8__) {
            vars__.emplace_back(lcm_sym11__[(1 - 1)]);
            for (int sym1__ = 2; sym1__ <= N; ++sym1__) {
              vars__.emplace_back(lcm_sym11__[(sym1__ - 1)]);}
          } 
        }
      } else {
        lcm_sym8__ = logical_gte(N, 1);
      }
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> log_lik;
      log_lik = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(log_lik, std::numeric_limits<double>::quiet_NaN());
      
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 8;
      if (lcm_sym8__) {
        current_statement__ = 7;
        assign(log_lik, cons_list(index_uni(1), nil_index_list()),
          normal_lpdf<false>(brain[(1 - 1)], lcm_sym11__[(1 - 1)], 0.001),
          "assigning variable log_lik");
        for (int i = 2; i <= N; ++i) {
          current_statement__ = 7;
          assign(log_lik, cons_list(index_uni(i), nil_index_list()),
            normal_lpdf<false>(brain[(i - 1)], lcm_sym11__[(i - 1)], 0.001),
            "assigning variable log_lik");}
      } 
      current_statement__ = 9;
      sigma = 0.001;
      if (lcm_sym8__) {
        vars__.emplace_back(log_lik[(1 - 1)]);
        for (int sym1__ = 2; sym1__ <= N; ++sym1__) {
          vars__.emplace_back(log_lik[(sym1__ - 1)]);}
      } 
      vars__.emplace_back(0.001);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      double lcm_sym6__;
      double lcm_sym5__;
      double lcm_sym4__;
      double lcm_sym3__;
      int lcm_sym2__;
      int lcm_sym1__;
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double a;
      a = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      a = context__.vals_r("a")[(1 - 1)];
      Eigen::Matrix<double, -1, 1> b;
      b = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(b, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<double> b_flat__;
        current_statement__ = 2;
        assign(b_flat__, nil_index_list(), context__.vals_r("b"),
          "assigning variable b_flat__");
        current_statement__ = 2;
        pos__ = 1;
        lcm_sym1__ = logical_gte(K, 1);
        if (lcm_sym1__) {
          current_statement__ = 2;
          assign(b, cons_list(index_uni(1), nil_index_list()),
            b_flat__[(1 - 1)], "assigning variable b");
          current_statement__ = 2;
          pos__ = 2;
          for (int sym1__ = 2; sym1__ <= K; ++sym1__) {
            current_statement__ = 2;
            assign(b, cons_list(index_uni(sym1__), nil_index_list()),
              b_flat__[(pos__ - 1)], "assigning variable b");
            current_statement__ = 2;
            pos__ = (pos__ + 1);}
        } 
      }
      double log_sigma;
      log_sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      log_sigma = context__.vals_r("log_sigma")[(1 - 1)];
      vars__.emplace_back(a);
      if (lcm_sym1__) {
        vars__.emplace_back(b[(1 - 1)]);
        for (int sym1__ = 2; sym1__ <= K; ++sym1__) {
          vars__.emplace_back(b[(sym1__ - 1)]);}
      } 
      vars__.emplace_back(log_sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("a");
    names__.emplace_back("b");
    names__.emplace_back("log_sigma");
    names__.emplace_back("mu");
    names__.emplace_back("log_lik");
    names__.emplace_back("sigma");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "a");
    for (int sym31__ = 1; sym31__ <= K; ++sym31__) {
      {
        param_names__.emplace_back(std::string() + "b" + '.' + std::to_string(sym31__));
      }}
    param_names__.emplace_back(std::string() + "log_sigma");
    if (emit_transformed_parameters__) {
      for (int sym31__ = 1; sym31__ <= N; ++sym31__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym31__));
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym31__ = 1; sym31__ <= N; ++sym31__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym31__));
        }}
      param_names__.emplace_back(std::string() + "sigma");
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "a");
    for (int sym31__ = 1; sym31__ <= K; ++sym31__) {
      {
        param_names__.emplace_back(std::string() + "b" + '.' + std::to_string(sym31__));
      }}
    param_names__.emplace_back(std::string() + "log_sigma");
    if (emit_transformed_parameters__) {
      for (int sym31__ = 1; sym31__ <= N; ++sym31__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym31__));
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym31__ = 1; sym31__ <= N; ++sym31__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym31__));
        }}
      param_names__.emplace_back(std::string() + "sigma");
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"log_sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"log_sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  

    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        

};
}
using stan_model = m7x462s_model_namespace::m7x462s_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return m7x462s_model_namespace::profiles__;
}

#endif


